"""Version string for the bundled `se` binary.

Generated by scripts/build.sh — do NOT edit by hand. The committed
default lives in version control; this file is restored after build.
"""
__version__ = "e34d9a0-dirty"
__commit__ = "e34d9a0"
__build_date__ = "2026-05-16T13:51:30Z"
