#!/usr/bin/env python3
"""
Fix-Bug Phase 3: Run pre-merge check, push branch, create PR.

Usage: python3 fix_bug_pr.py <id> [--target-repo <path>] [--actor <name>]
                              [--title <title>] [--draft]
Output: JSON {id, pr_url, pr_number, idempotent?}
Exit codes:
  0 = PR created (or already exists — idempotent)
  1 = preconditions not met (verify not passed, wrong phase)
  2 = pre-merge check / git push / gh pr create failed
"""
import argparse
import json
import os
import re
import subprocess
import sys
import time


def wisp_read(issue_id: str, key: str, cwd: str) -> str:
    r = subprocess.run(
        ["grava", "wisp", "read", issue_id, key],
        capture_output=True, text=True, cwd=cwd,
    )
    return r.stdout.strip() if r.returncode == 0 else ""


def wisp_write(issue_id: str, key: str, value: str, cwd: str) -> None:
    subprocess.run(
        ["grava", "wisp", "write", issue_id, key, value],
        capture_output=True, cwd=cwd,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("id", help="Grava bug issue ID")
    parser.add_argument("--target-repo", default=".")
    parser.add_argument("--actor", default="fix-bug-pr-creator")
    parser.add_argument("--title", default=None)
    parser.add_argument("--draft", action="store_true")
    args = parser.parse_args()

    cwd = args.target_repo
    worktree = os.path.join(cwd, ".worktree", args.id)
    branch = f"grava/{args.id}"

    # 1. Precondition: self-verify must have passed
    phase = wisp_read(args.id, "pipeline_phase", cwd)
    verify_result = wisp_read(args.id, "self_verify_result", cwd)

    if phase not in ("coding_complete",) and verify_result != "pass":
        print(
            f"ERROR: self-verify not passed for {args.id}.\n"
            f"  pipeline_phase={phase!r}, self_verify_result={verify_result!r}\n"
            f"  Run fix_bug_verify.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    # 2. Idempotency — PR already created?
    if phase in ("pr_created", "pr_awaiting_merge"):
        pr_url = wisp_read(args.id, "pr_url", cwd)
        pr_number = wisp_read(args.id, "pr_number", cwd)
        print(f"PR already created: {pr_url}")
        print(json.dumps({"id": args.id, "pr_url": pr_url, "pr_number": pr_number, "idempotent": True}))
        sys.exit(0)

    # 3. Optional pre-merge check script
    check_script = os.path.join(cwd, "scripts", "pre-merge-check.sh")
    if os.path.isfile(check_script):
        r = subprocess.run(["bash", check_script], capture_output=True, text=True, cwd=cwd)
        if r.returncode != 0:
            print(f"ERROR: pre-merge check failed:\n{r.stdout}\n{r.stderr}", file=sys.stderr)
            sys.exit(2)
    else:
        print("(No scripts/pre-merge-check.sh found — skipping pre-merge check)")

    # 4. Push branch
    if not os.path.isdir(worktree):
        print(f"ERROR: worktree not found: {worktree}", file=sys.stderr)
        sys.exit(1)

    push_r = subprocess.run(
        ["git", "push", "-u", "origin", branch],
        capture_output=True, text=True, cwd=worktree,
    )
    if push_r.returncode != 0:
        print(f"ERROR: git push failed:\n{push_r.stderr}", file=sys.stderr)
        sys.exit(2)

    # 5. Resolve PR title from issue
    show_r = subprocess.run(
        ["grava", "show", args.id, "--json"],
        capture_output=True, text=True, cwd=cwd,
    )
    issue_title = args.title or args.id
    issue_desc = ""
    if show_r.returncode == 0:
        try:
            data = json.loads(show_r.stdout)
            issue_title = args.title or data.get("title", args.id)
            issue_desc = (data.get("description") or "")[:500]
        except Exception:
            pass

    pr_title = f"fix: {issue_title} ({args.id})"
    pr_body = (
        f"Fixes {args.id}\n\n"
        f"## Summary\n{issue_title}\n\n"
        + (f"## Issue\n{issue_desc}\n\n" if issue_desc else "")
        + "🤖 Generated by fix-bug pipeline"
    )

    # 6. Create PR
    gh_cmd = [
        "gh", "pr", "create",
        "--title", pr_title,
        "--body", pr_body,
        "--base", "main",
        "--head", branch,
    ]
    if args.draft:
        gh_cmd.append("--draft")

    gh_r = subprocess.run(gh_cmd, capture_output=True, text=True, cwd=worktree)
    if gh_r.returncode != 0:
        print(f"ERROR: gh pr create failed:\n{gh_r.stderr}", file=sys.stderr)
        sys.exit(2)

    # Parse PR URL from stdout
    output = gh_r.stdout.strip()
    url_match = re.search(r"https://github\.com/\S+/pull/\d+", output)
    pr_url = url_match.group(0) if url_match else output.split("\n")[-1].strip()

    # Get PR number
    num_r = subprocess.run(
        ["gh", "pr", "view", "--json", "number", "-q", ".number"],
        capture_output=True, text=True, cwd=worktree,
    )
    pr_number = num_r.stdout.strip() if num_r.returncode == 0 else ""

    # 7. Write wisps
    wisp_write(args.id, "pr_url", pr_url, cwd)
    wisp_write(args.id, "pr_number", pr_number, cwd)
    wisp_write(args.id, "pr_awaiting_merge_since", str(int(time.time())), cwd)
    wisp_write(args.id, "pipeline_phase", "pr_created", cwd)
    wisp_write(args.id, "orchestrator_heartbeat", str(int(time.time())), cwd)

    # Try structured signal (compatible with /ship watcher)
    subprocess.run(
        ["grava", "signal", "PR_CREATED",
         "--issue", args.id, "--payload", pr_url, "--actor", args.actor],
        capture_output=True, cwd=cwd,
    )

    subprocess.run(
        ["grava", "label", args.id, "--add", "pr-created"],
        capture_output=True, cwd=cwd,
    )
    subprocess.run(
        ["grava", "commit", "-m", f"fix-bug: {args.id} PR created at {pr_url}"],
        capture_output=True, cwd=cwd,
    )

    print(json.dumps({"id": args.id, "pr_url": pr_url, "pr_number": pr_number}))


if __name__ == "__main__":
    main()
