#!/usr/bin/env bash
# Build a standalone `se` binary for the current platform using PyInstaller.
#
# Produces:
#   dist/se-<os>-<arch>/se                       — runnable binary
#   dist/se-<os>-<arch>.tar.gz                   — distributable tarball
#
# Usage:
#   bash scripts/build.sh                        # builds for current host
#   bash scripts/build.sh --version v0.1.0       # stamps version into name
#
# Requires: python3 (3.10+), pip. Auto-installs PyInstaller into a venv.

set -euo pipefail

VERSION="${SE_VERSION:-}"
while [ $# -gt 0 ]; do
    case "$1" in
        --version) VERSION="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,15p' "$0"; exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ── version metadata ──────────────────────────────────────────────────────────
# Priority: --version flag → SE_VERSION env → git describe → "0.0.0-dev".
if [ -z "$VERSION" ]; then
    if git rev-parse --git-dir >/dev/null 2>&1; then
        VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo "0.0.0-dev")"
    else
        VERSION="0.0.0-dev"
    fi
fi

COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo "▸ version: $VERSION (commit $COMMIT, built $BUILD_DATE)"

# Stamp the version file. Restore on exit so dev installs stay at 0.0.0-dev.
VERSION_FILE="$REPO_ROOT/cli/_version.py"
VERSION_BACKUP="$(mktemp)"
cp "$VERSION_FILE" "$VERSION_BACKUP"
trap 'mv "$VERSION_BACKUP" "$VERSION_FILE"' EXIT

cat > "$VERSION_FILE" <<EOF
"""Version string for the bundled \`se\` binary.

Generated by scripts/build.sh — do NOT edit by hand. The committed
default lives in version control; this file is restored after build.
"""
__version__ = "$VERSION"
__commit__ = "$COMMIT"
__build_date__ = "$BUILD_DATE"
EOF

# ── platform ──────────────────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$OS" in
    darwin) OS_TAG="darwin" ;;
    *) echo "unsupported OS: $OS (macOS only for now)" >&2; exit 1 ;;
esac

ARCH="$(uname -m)"
case "$ARCH" in
    x86_64|amd64) ARCH_TAG="x64" ;;
    arm64|aarch64) ARCH_TAG="arm64" ;;
    *) echo "unsupported arch: $ARCH" >&2; exit 1 ;;
esac

NAME="se-${OS_TAG}-${ARCH_TAG}"

echo "▸ building $NAME"

# ── venv ──────────────────────────────────────────────────────────────────────
VENV="$REPO_ROOT/.build-venv"
if [ ! -d "$VENV" ]; then
    python3 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"

pip install --quiet --upgrade pip
pip install --quiet pyinstaller pyyaml markdown markdownify requests

# ── data bundling ─────────────────────────────────────────────────────────────
#
# PyInstaller extracts everything under sys._MEIPASS at runtime. The `se`
# entrypoint resolves _repo_root() to that dir, so all dispatched scripts
# must be bundled flat next to it.
#
# Trailing :<dest> places the source path under that dir inside the bundle.

ADD_DATA=(
    "--add-data" "$REPO_ROOT/agents:agents"
    "--add-data" "$REPO_ROOT/cli/_version.py:cli"
    "--add-data" "$REPO_ROOT/download_project_pages.py:."
    "--add-data" "$REPO_ROOT/upload_project_pages.py:."
    "--add-data" "$REPO_ROOT/upload_wiki_page.py:."
)

# ── build ─────────────────────────────────────────────────────────────────────
rm -rf "$REPO_ROOT/build" "$REPO_ROOT/dist/$NAME" "$REPO_ROOT/dist/$NAME.tar.gz"

pyinstaller \
    --noconfirm \
    --onefile \
    --name "se" \
    --distpath "$REPO_ROOT/dist/$NAME" \
    --workpath "$REPO_ROOT/build/$NAME" \
    --specpath "$REPO_ROOT/build/$NAME" \
    "${ADD_DATA[@]}" \
    --hidden-import yaml \
    --hidden-import markdown \
    --hidden-import markdownify \
    --hidden-import requests \
    "$REPO_ROOT/cli/se"

# ── smoke test ────────────────────────────────────────────────────────────────
BIN="$REPO_ROOT/dist/$NAME/se"
"$BIN" --help >/dev/null
echo "✓ binary runs: $BIN"

# ── package ───────────────────────────────────────────────────────────────────
( cd "$REPO_ROOT/dist" && tar -czf "$NAME.tar.gz" -C "$NAME" se )
echo "✓ tarball:    $REPO_ROOT/dist/$NAME.tar.gz"

# ── checksum ──────────────────────────────────────────────────────────────────
( cd "$REPO_ROOT/dist" && shasum -a 256 "$NAME.tar.gz" > "$NAME.tar.gz.sha256" )
echo "✓ sha256:     $(cat "$REPO_ROOT/dist/$NAME.tar.gz.sha256")"

deactivate

echo ""
echo "next: install locally with"
echo "    sudo install -m 0755 $BIN /usr/local/bin/se"
